### ISSUE TITLE
Backspace on mobile

### ISSUE THREAD

**Issue by kamnakis** [dammy001/vue-split-input#38]
When I click backspace on mobile device it doesn't focus the previous input box.

**Comment by kamnakis** [comment]
Here you go: https://github.com/kamnakis/vue-split-input-test

Run
```sh
npm i
npm run dev
```

You can use your local IP to run it on mobile device (must be connected to same network)

**Comment by kamnakis** [comment]
I run a few tests and figured that on mobile the `event.code` is undefined, maybe try using `event.key` instead for the `Backspace` event.

https://github.com/dammy001/vue-split-input/blob/next/components/SplitInput.vue#L103

**Comment by dammy001** [comment]
@kamnakis I think the issue is OS-specific because I just tried with IOS and it works perfectly. I'll fix the issue ASAP.
Thanks.

**Comment by kamnakis** [comment]
Hmmm yes it might be! I tested on Huawei phone (Chrome)

**Comment by dammy001** [comment]
@kamnakis please update and confirm if #39 fixed the issue

**Comment by kamnakis** [comment]
I updated but I get a typescipt error! It works though!
![image](https://user-images.githubusercontent.com/33131460/152646305-96baa3ce-eed2-4bf3-b51a-c50bee139ea5.png)

**Comment by dammy001** [comment]
@kamnakis will make an update soon. Thanks for the update.

**Comment by dammy001** [comment]
fixed!! I can close the issue now

**Comment by kamnakis** [comment]
Typescript still breaks! :/ There's a type.ts file mssing

**Comment by dammy001** [comment]
@kamnakis pushed a fix for that already 🤌🏽🤌🏽🤌🏽... Thanks

**Comment by kamnakis** [comment]
@dammy001 It works now but you forgot to add the Plugin types :P

I had to do this to get no errors!
```ts
import { Plugin } from 'vue'
app.use(SplitInput as Plugin)
```

Thanks anyway!

**Comment by dammy001** [comment]
@kamnakis all issues are fixed now. update to the latest version. Thanks

**Comment by kamnakis** [comment]
> @kamnakis all issues are fixed now. update to the latest version. Thanks

I can confirm eveything works perfect now! Thanks!
